name = "DisplayBAMF"
uuid = "be7a214b-1432-4e9f-bf2f-568e81c3a5dc"
authors = ["StapleGrain <StapleGrain@github.com>"]
version = "0.1.0"

[deps]
BayesMultiFit = "b46b6485-dee9-4ab3-ae4f-5a975ad04c76"
ImageView = "86fae568-95e7-573e-a6b2-d8a6b900c9ef"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
